version: 2

macros:
  - name: categorizar_importe
    description: "Macro que aplica la lógica de segmentación de pedidos según su valor."
    arguments:
      - name: columna
        description: "Campo numérico que contiene el importe bruto a evaluar."